//! The `plum_actions` attribute macro: applied to an `impl` block on the core model,
//! it passes through the original impl unchanged and generates a
//! `#[wasm_bindgen] impl Wasm{Name}` block that forwards each qualifying pub method.
//!
//! Skips:
//! - Constructors (no `&self` receiver)
//! - Signal/memo accessors (return `RwSignal<...>`, `Memo<...>`, `ReadSignal<...>`, `Signal<...>`)
//! - Methods already generated by the derive (`dispose`, `unwatch`, `watch_*`)

use proc_macro2::TokenStream;
use quote::{quote, ToTokens};
use syn::ImplItemFn;

use crate::naming::{snake_to_camel, wasm_class_name};

pub fn expand(input: TokenStream) -> TokenStream {
    let item_impl: syn::ItemImpl = match syn::parse2(input.clone()) {
        Ok(i) => i,
        Err(e) => return e.to_compile_error(),
    };

    let self_type_name = match &*item_impl.self_ty {
        syn::Type::Path(tp) => match tp.path.segments.last() {
            Some(seg) => seg.ident.to_string(),
            None => {
                return syn::Error::new_spanned(
                    &item_impl.self_ty,
                    "plum_actions: cannot determine self type",
                )
                .to_compile_error();
            }
        },
        _ => {
            return syn::Error::new_spanned(
                &item_impl.self_ty,
                "plum_actions: self type must be a simple path",
            )
            .to_compile_error();
        }
    };

    let wasm_name_str = wasm_class_name(&self_type_name);
    let wasm_name_ident = syn::Ident::new(&wasm_name_str, proc_macro2::Span::call_site());

    let methods: Vec<TokenStream> = item_impl
        .items
        .iter()
        .filter_map(|item| match item {
            syn::ImplItem::Fn(func) => expand_method(func),
            _ => None,
        })
        .collect();

    // Use original tokens for pass-through (avoids re-rendering issues).
    quote! {
        #input

        #[cfg(feature = "plum")]
        #[::wasm_bindgen::prelude::wasm_bindgen]
        impl #wasm_name_ident {
            #(#methods)*
        }
    }
}

fn expand_method(func: &ImplItemFn) -> Option<TokenStream> {
    // Must be pub
    if !matches!(func.vis, syn::Visibility::Public(_)) {
        return None;
    }

    let name = &func.sig.ident;
    let name_str = name.to_string();

    // Skip methods already generated by the derive
    if name_str == "dispose" || name_str == "unwatch" || name_str.starts_with("watch_") {
        return None;
    }

    // Must take &self (skip constructors, associated functions)
    let has_self = func.sig.inputs.first().is_some_and(|p| {
        matches!(
            p,
            syn::FnArg::Receiver(r) if r.reference.is_some() && r.mutability.is_none()
        )
    });
    if !has_self {
        return None;
    }

    // Skip signal/memo accessors (they're exposed via the watch mechanism)
    if returns_signal_type(&func.sig.output) {
        return None;
    }

    let js_name = snake_to_camel(&name_str);
    let js_name_lit = js_name.clone();

    // Collect non-self parameters
    let params: Vec<&syn::FnArg> = func
        .sig
        .inputs
        .iter()
        .skip(1) // skip &self
        .collect();

    let is_async = func.sig.asyncness.is_some();

    if is_async {
        // Async method: fire-and-forget via spawn_local.
        // The JS side gets a void return; callers should rely on reactive
        // stores to observe the result, or use a settle/poll pattern.
        let (wasm_params, conversions, call_args) =
            build_params_and_conversion_async(&params, &name_str);

        return Some(quote! {
            #[::wasm_bindgen::prelude::wasm_bindgen(js_name = #js_name_lit)]
            pub fn #name(&self, #wasm_params) {
                #(#conversions)*
                let core = self.core.clone();
                ::any_spawner::Executor::spawn_local(async move {
                    let _ = core.#name(#(#call_args),*).await;
                });
            }
        });
    }

    let ret_type = &func.sig.output;
    let (wasm_params, conversions, call_args) = build_params_and_conversion(&params, &name_str);

    // Determine if return type needs serde conversion
    let ret_str = match ret_type {
        syn::ReturnType::Type(_, ty) => ty.to_token_stream().to_string(),
        _ => String::new(),
    };
    let ret_normalized = ret_str.replace(" ", "");

    if ret_normalized.is_empty() || is_native_wasm_return_type(&ret_normalized) {
        // Native return type: pass through
        return Some(quote! {
            #[::wasm_bindgen::prelude::wasm_bindgen(js_name = #js_name_lit)]
            pub fn #name(&self, #wasm_params) #ret_type {
                #(#conversions)*
                self.core.#name(#(#call_args),*)
            }
        });
    }

    // Non-native return type: convert via serde_wasm_bindgen
    if ret_normalized.starts_with("Option<") && ret_normalized.ends_with('>') {
        // Option<T> -> Option<JsValue>
        Some(quote! {
            #[::wasm_bindgen::prelude::wasm_bindgen(js_name = #js_name_lit)]
            pub fn #name(&self, #wasm_params) -> Option<::wasm_bindgen::JsValue> {
                #(#conversions)*
                self.core.#name(#(#call_args),*).map(|v| ::serde_wasm_bindgen::to_value(&v).unwrap())
            }
        })
    } else {
        // Vec<T> or bare type -> JsValue
        Some(quote! {
            #[::wasm_bindgen::prelude::wasm_bindgen(js_name = #js_name_lit)]
            pub fn #name(&self, #wasm_params) -> ::wasm_bindgen::JsValue {
                #(#conversions)*
                ::serde_wasm_bindgen::to_value(&self.core.#name(#(#call_args),*)).unwrap()
            }
        })
    }
}

/// Check if the return type is a signal/memo type (RwSignal, Memo, ReadSignal, Signal).
fn returns_signal_type(output: &syn::ReturnType) -> bool {
    if let syn::ReturnType::Type(_, ty) = output {
        if let syn::Type::Path(tp) = &**ty {
            if let Some(seg) = tp.path.segments.last() {
                return matches!(
                    seg.ident.to_string().as_str(),
                    "RwSignal" | "Memo" | "ReadSignal" | "Signal"
                );
            }
        }
    }
    false
}

/// For each parameter, decide whether to pass through (wasm-bindgen native type)
/// or convert via serde (accept as String, deserialize).
fn build_params_and_conversion(
    params: &[&syn::FnArg],
    method_name: &str,
) -> (TokenStream, Vec<TokenStream>, Vec<TokenStream>) {
    let mut wasm_params = proc_macro2::TokenStream::new();
    let mut conversions = Vec::new();
    let mut call_args = Vec::new();

    for param in params {
        if let syn::FnArg::Typed(pat_type) = param {
            let param_name = if let syn::Pat::Ident(pi) = &*pat_type.pat {
                pi.ident.clone()
            } else {
                continue;
            };
            let param_type = &pat_type.ty;
            let type_str = param_type.to_token_stream().to_string();

            if is_native_wasm_type(&type_str) {
                // Pass through: same param type, no conversion
                let ty = param_type;
                wasm_params.extend(quote! { #param_name : #ty , });
                call_args.push(quote! { #param_name });
            } else {
                // Non-native: accept as String, convert via serde_json
                let orig_type = param_type;
                let local_name = syn::Ident::new(
                    &format!("_plum_{}", param_name),
                    proc_macro2::Span::call_site(),
                );
                wasm_params.extend(quote! { #param_name : String , });
                conversions.push(quote! {
                    let #local_name : #orig_type = ::serde_json::from_value(
                        ::serde_json::Value::String(#param_name.clone())
                    ).unwrap_or_else(|e| panic!("plum: failed to deserialize argument for `{}`: {}", #method_name, e));
                });
                call_args.push(quote! { #local_name });
            }
        }
    }

    (wasm_params, conversions, call_args)
}

/// Build params and conversion for sync methods (pass-through or serde deserialize).
/// For async methods, `&str` params are converted to `String` in the wasm signature
/// and `.as_str()` is used at the call site (since the value must be moved into
/// the async block).
fn build_params_and_conversion_async(
    params: &[&syn::FnArg],
    method_name: &str,
) -> (TokenStream, Vec<TokenStream>, Vec<TokenStream>) {
    let mut wasm_params = proc_macro2::TokenStream::new();
    let mut conversions = Vec::new();
    let mut call_args = Vec::new();

    for param in params {
        if let syn::FnArg::Typed(pat_type) = param {
            let param_name = if let syn::Pat::Ident(pi) = &*pat_type.pat {
                pi.ident.clone()
            } else {
                continue;
            };
            let param_type = &pat_type.ty;
            let type_str = param_type.to_token_stream().to_string();

            if type_str.trim() == "& str" {
                // &str in async: accept String, pass .as_str() at call site
                wasm_params.extend(quote! { #param_name : String , });
                call_args.push(quote! { #param_name .as_str() });
            } else if is_native_wasm_type(&type_str) {
                // Pass through: same param type, no conversion
                let ty = param_type;
                wasm_params.extend(quote! { #param_name : #ty , });
                call_args.push(quote! { #param_name });
            } else {
                // Non-native: accept as String, convert via serde_json before spawn
                let orig_type = param_type;
                let local_name = syn::Ident::new(
                    &format!("_plum_{}", param_name),
                    proc_macro2::Span::call_site(),
                );
                wasm_params.extend(quote! { #param_name : String , });
                conversions.push(quote! {
                    let #local_name : #orig_type = ::serde_json::from_value(
                        ::serde_json::Value::String(#param_name.clone())
                    ).unwrap_or_else(|e| panic!("plum: failed to deserialize argument for `{}`: {}", #method_name, e));
                });
                call_args.push(quote! { #local_name });
            }
        }
    }

    (wasm_params, conversions, call_args)
}

/// Types that wasm-bindgen can handle natively without conversion.
fn is_native_wasm_type(type_str: &str) -> bool {
    matches!(
        type_str.trim(),
        "& str" | "String" | "i32" | "u32" | "u64" | "i64" | "bool" | "f64" | "f32"
    )
}

/// Check if a return type is natively supported by wasm-bindgen (no conversion needed).
fn is_native_wasm_return_type(normalized: &str) -> bool {
    // Simple primitives and String
    if matches!(
        normalized,
        "i32" | "u32" | "u64" | "i64" | "bool" | "f64" | "f32" | "String" | "JsValue"
    ) {
        return true;
    }
    // Option<primitive>
    if let Some(inner) = normalized
        .strip_prefix("Option<")
        .and_then(|s| s.strip_suffix('>'))
    {
        return matches!(
            inner,
            "i32" | "u32" | "u64" | "i64" | "bool" | "f64" | "f32" | "String" | "JsValue"
        );
    }
    // Vec<primitive>
    if let Some(inner) = normalized
        .strip_prefix("Vec<")
        .and_then(|s| s.strip_suffix('>'))
    {
        return matches!(
            inner,
            "i32" | "u32" | "u64" | "i64" | "bool" | "f64" | "f32" | "String"
        );
    }
    false
}
